apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-service
        image: mehike/auth_service:0.0.1
        #command: [ "sh", "-c"]
        #args:
        #- while true; do
        #    echo -en '\n';
        #    printenv FB_APPID FB_SECRET GOOGLE_APPID;
        #    printenv GOOGLE_SECRET POSTGRES_DB POSTGRES_HOST POSTGRES_PORT;
        #    sleep 5;
        #  done;
        ports:
        - containerPort: 8085
        env:
        - name: CONFIG_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-host
        - name: CONFIG_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-port
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              name: eureka
              key: eureka-uri
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresdb
              key: database-host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresdb
              key: database-port
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: auth
              key: database-name
        - name: FB_APPID
          valueFrom:
            secretKeyRef:
              name: auth
              key: fb-clientid
        - name: FB_SECRET
          valueFrom:
            secretKeyRef:
              name: auth
              key: fb-clientsecret
        - name: GOOGLE_APPID
          valueFrom:
            secretKeyRef:
              name: auth
              key: google-id
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: auth
              key: google-secret
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Tallinn
            