apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-service
        image: mehike/auth-service:0.0.1
        ports:
        - containerPort: 8085
        env:
        - name: CONFIG_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-host
        - name: CONFIG_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-port
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              name: eureka
              key: eureka-uri
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-user
        - name: FB_CLIENTID
          valueFrom:
            secretKeyRef:
              name: auth
              key: fb-clientid
        - name: FB_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: auth
              key: fb-clientsecret
        - name: GITHUB_CLIENTID
          valueFrom:
            secretKeyRef:
              name: auth
              key: github-clientid
        - name: GITHUB_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: auth
              key: github-clientsecret
        - name: LINKEDIN_CLIENTID
          valueFrom:
            secretKeyRef:
              name: auth
              key: linkedin-clientid
        - name: LINKEDIN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth
              key: linkedin-clientsecret
        - name: GOOGLE_CLIENTID
          valueFrom:
            secretKeyRef:
              name: auth
              key: google-clientid
        - name: GOOGLE_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: auth
              key: google-clientsecret
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Tallinn

