apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  #externalIPs:
  #- 192.168.1.156
  #- 88.196.63.92
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: auth
  type: NodePort
